#!/bin/bash
set -e

echo "Creating database and investments for $DB_INVESTMENTS"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER "$DB_INVESTMENTS_OWNER" WITH PASSWORD '$DB_INVESTMENTS_PASSWORD';
  CREATE DATABASE "$DB_INVESTMENTS";
  ALTER DATABASE "$DB_INVESTMENTS" OWNER TO "$DB_INVESTMENTS_OWNER";
EOSQL
